<a href="https://colab.research.google.com/github/AIVIETNAM-AIO-HUYTRUONG/Artificial-Intelligence/blob/basic/02.%20Essential%20NumPy%20and%20Pandas/Chapter%202%3A%20Getting%20Started%20with%20NumPy%20Arrays/02_creating_arrays_from_python_lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Creating Arrays from Python Lists**

- Mặc dù NumPy cung cấp các hàm chuyên biệt để tạo mảng, một cách khởi đầu rất phổ biến là chuyển đổi các **cấu trúc dữ liệu Python (Python data structures)** hiện có, đặc biệt là list, thành NumPy array. Đây thường là bước đầu tiên khi bạn đã có dữ liệu được tải hoặc tạo bằng mã Python tiêu chuẩn.

- Hàm chính được sử dụng cho quá trình chuyển đổi là `np.array()`.

## **1. Creating 1D Arrays from Lists**

- Giả sử bạn có một list Python đơn giản gồm các số:

In [ ]:
import numpy as np

# A standard Python list
python_list = [5, 10, 15, 20, 25]
print(f"Original Python list: {python_list}")
print(f"Type: {type(python_list)}")

# Convert the list to a NumPy array
numpy_array = np.array(python_list)

print(f"Converted NumPy array: {numpy_array}")
print(f"Type: {type(numpy_array)}")
print(f"Array's data type (dtype): {numpy_array.dtype}")

Original Python list: [5, 10, 15, 20, 25]
Type: <class 'list'>
Converted NumPy array: [ 5 10 15 20 25]
Type: <class 'numpy.ndarray'>
Array's data type (dtype): int64


- Khi chạy đoạn mã này, bạn sẽ nhận thấy một vài điểm:
  1. Hàm `np.array()` nhận list Python làm input.
  2. Output `numpy_array` không còn là một list Python tiêu chuẩn mà là một object thuộc kiểu `numpy.ndarray`. Đây chính là **mảng N chiều (N-dimensional array)** mà chúng ta đã thảo luận.
  3. NumPy tự động suy luận **kiểu dữ liệu (data type)** của các phần tử. Vì tất cả các phần tử đều là số nguyên, array kết quả có `dtype` là `int64` (kiểu integer chính xác, chẳng hạn như `int32` hoặc `int64`, có thể khác đôi chút tùy thuộc vào hệ thống của bạn).

- Khả năng **tự động phát hiện kiểu dữ liệu (automatic type detection)** này rất tiện lợi. Nếu list của bạn chứa các **số thực dấu phẩy động (floating-point numbers)**, NumPy sẽ tạo một float array:

In [ ]:
float_list = [1.0, 2.5, 3.7, 4.2]
float_array = np.array(float_list)
print(f"Float array: {float_array}")
print(f"Float array dtype: {float_array.dtype}") # Likely float64

Float array: [1.  2.5 3.7 4.2]
Float array dtype: float64


## **2. Creating Multi-dimensional Arrays from Nested Lists**

- NumPy array có thể có nhiều hơn một dimension. Bạn có thể tạo **mảng nhiều chiều (multi-dimensional arrays)** bằng cách truyền các **list lồng nhau (nested Python lists)** — tức là các list chứa những list khác — vào `np.array()`.

In [ ]:
# A nested Python list (list of lists)
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(f"Original nested list:\n{nested_list}")

# Convert to a 2D NumPy array
numpy_2d_array = np.array(nested_list)

print(f"Converted 2D NumPy array:\n{numpy_2d_array}")
print(f"Array shape: {numpy_2d_array.shape}") # Output: (3, 3) -> 3 rows, 3 columns
print(f"Array dimensions: {numpy_2d_array.ndim}") # Output: 2
print(f"Array dtype: {numpy_2d_array.dtype}") # Output: int64 (usually)

Original nested list:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Converted 2D NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array shape: (3, 3)
Array dimensions: 2
Array dtype: int64


- Ở đây, list gồm ba list, mỗi list chứa số nguyên, được chuyển thành một array 2 chiều - hay một **matrix** - gồm 3 hàng và 3 cột. NumPy sắp xếp dữ liệu tương ứng theo cấu trúc này.

- Để NumPy có thể tạo một multi-dimensional array tiêu chuẩn một cách hiệu quả, các list bên trong phải có cùng độ dài. Nếu không, NumPy có thể tạo một array có `dtype=object`, trong đó mỗi phần từ là một Python object, chẳng hạn như một list. Điều này nhìn chung làm mất đi các lợi ích về hiệu suất của NumPy array.

In [ ]:
# Example of an uneven list (use with caution)
uneven_list = [[1, 2], [3, 4, 5]]

# NumPy may create an object array
# Note: Behavior might change slightly across NumPy versions.
# Explicitly setting dtype=object ensures this behavior if needed.
object_array = np.array(uneven_list, dtype=object)

print(f"Array from uneven list:\n{object_array}")
print(f"Array dtype: {object_array.dtype}") # Output: object

Array from uneven list:
[list([1, 2]) list([3, 4, 5])]
Array dtype: object


## **3. Specifying the Data Type (`dtype`)**

- Mặc dù khả năng **suy luận kiểu dữ liệu tự động (automatic type inference)** của NumPy rất hữu ích, đôi khi bạn cần kiểm soát rõ **data type** của array. Bạn có thể chỉ định kiểu mong muốn bằng argument `dtype` trong hàm `np.array()`. Điều này hữu ích cho:

  - **Memory Management**: Các data type nhỏ hơn, chẳng hạn như `float32` thay vì `float64`, hoặc `int8` thay vì `int64`, sử dụng ít bộ nhớ hơn.
  - **Precision**: Đảm bảo các phép tính được thực hiện với độ chính xác floating-point phù hợp.
  - **Compatibility**: Khớp data type với yêu cầu của các thư viện hoặc hàm khác.

- Dưới đây là cách tạo một array gồm các floating-point number từ một list số nguyên.

In [ ]:
integer_list = [1, 2, 3, 4]

# Create a float array from integers
float_array = np.array(integer_list, dtype=float) # or np.float64, np.float32 etc.

print(f"Original integer list: {integer_list}")
print(f"Converted float array: {float_array}")
print(f"Array dtype: {float_array.dtype}") # Output: float64 (or specified float type)

# Create an integer array with a smaller integer type
int8_array = np.array(integer_list, dtype=np.int8)
print(f"Converted int8 array: {int8_array}")
print(f"Array dtype: {int8_array.dtype}") # Output: int8

Original integer list: [1, 2, 3, 4]
Converted float array: [1. 2. 3. 4.]
Array dtype: float64
Converted int8 array: [1 2 3 4]
Array dtype: int8


- Một số NumPy data type phổ biến bao gồm `np.int8`, `np.int16`, `np.int32`, `np.int64`, `np.uint8` — **số nguyên không dấu (unsigned integer)**, `np.float32`, `np.float64`, `np.complex64`, `np.complex128`, `np.bool_` và `np.object_.`

- Việc lựa chọn `dtype` phù hợp rất quan trọng, đặc biệt khi làm việc với **tập dữ liệu lớn (large datasets)**.

- Chuyển đổi Python list là một cách nền tảng để bắt đầu làm việc với NumPy array, tạo ra cầu nối từ các Python data structure tiêu chuẩn sang những khả năng **tính toán số (numerical computing)** mạnh mẽ của NumPy. Trong phần tiếp theo, chúng ta sẽ tìm hiểu các hàm mà NumPy cung cấp để tạo array trực tiếp mà không cần một Python list có sẵn.